### ISSUE TITLE
replace_with give an attributeerror traceback

### ISSUE THREAD

**Issue by zhaoguixu** [gawel/pyquery#105]
```python
from pyquery.pyquery import PyQuery as pq
doc = pq("<html><div /></html>")
node = pq("<span />")
doc.replace_with(node)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyquery/pyquery.py", line 1324, in replace_with
    self.__class__(tag).before(value + (tag.tail or ''))
  File "/usr/local/lib/python2.7/dist-packages/pyquery/pyquery.py", line 1199, in before
    if not parent.text:
AttributeError: 'NoneType' object has no attribute 'text'

Why give an attributeerror traceback?

**Comment by gawel** [comment]
node must be a lxml element. doc.replace_with(node[0]) should work

**Comment by zhaoguixu** [comment]
It still does not work.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyquery/pyquery.py", line 1324, in replace_with
    self.__class__(tag).before(value + (tag.tail or ''))
TypeError: unsupported operand type(s) for +: 'lxml.etree._Element' and 'str'

================
It seems that you forget to check whether the parent of a tag is None?

**Comment by gawel** [comment]
Looks like I was wrong: must be text

https://github.com/gawel/pyquery/blob/master/tests/test_pyquery.py#L448

**Comment by zhaoguixu** [comment]
the docstring of the replace_with specifies it can be a PyQuery instance.
```python
 def replace_with(self, value):
       """replace nodes by value::
            >>> doc = PyQuery("<html><div /></html>")
            >>> node = PyQuery("<span />")
            >>> child = doc.find('div')
            >>> child.replace_with(node)
            [<div>]
            >>> print(doc)
            <html><span/></html>
        """
```
I think the root cause is you fail to check the parent of the tag.

**Comment by zhaoguixu** [comment]
The parent should be checked, do you think so?
=========
It still gives the traceback. 
doc.replace_with('<html>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyquery/pyquery.py", line 1324, in replace_with
    self.__class__(tag).before(value + (tag.tail or ''))
  File "/usr/local/lib/python2.7/dist-packages/pyquery/pyquery.py", line 1199, in before
    if not parent.text:
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by gawel** [comment]
Looks like you're deep in the code. Feel free to provide a fix. It will be merged except if it break tests. Even better if you provide new test(s)

**Comment by zhaoguixu** [comment]
I just simple check the code. Some other places also ignore the check. I will try. Thanks!
